Repository backube/pvc-transfer, pull requests merged in 2022-08, with the labels that each got.

#28 Remove rsync password
  transfer/rsync/client.go
  transfer/rsync/client_test.go
  transfer/rsync/server.go
  transfer/rsync/server_test.go
Labels: approved, lgtm, size/L

#29 Add Pranav to owners
  OWNERS
Labels: approved, lgtm, size/XS

#30 Consolidate certificate secrets
  transfer/rsync/rsync.go
  transfer/rsync/server.go
  transport/stunnel/client.go
  transport/stunnel/client_test.go
  transport/stunnel/server.go
  transport/stunnel/server_test.go
  transport/stunnel/stunnel.go
  transport/stunnel/stunnel_test.go
Labels: approved, lgtm, size/L

#31 Change loadbalancer endpoint to generic service
  endpoint/loadbalancer/loadbalancer.go
  endpoint/service/service.go
  endpoint/service/service_test.go
Labels: approved, lgtm, size/L

#32 Add ability to use existing PSK secrets
  transfer/rsync/client.go
  transfer/rsync/rsync.go
  transfer/rsync/server.go
  transfer/transfer.go
  transport/stunnel/client.go
  transport/stunnel/client_test.go
  transport/stunnel/server.go
  transport/stunnel/server_test.go
  transport/stunnel/stunnel.go
  transport/stunnel/stunnel_test.go
  transport/tls/certs/generate.go
  transport/transport.go
Labels: approved, lgtm, size/XL
