Repository backube/pvc-transfer, pull requests merged in 2022-07, with the labels that each got.

#24 minor fixes in rsync
  transfer/rsync/command_options.go
  transfer/rsync/server.go
Labels: approved, lgtm, size/XS

#25 Add retries for rsync
  transfer/rsync/client.go
Labels: approved, lgtm, size/M

#26 Enable using a custom rsync image
  transfer/rsync/client.go
  transfer/rsync/rsync.go
  transfer/rsync/server.go
  transfer/transfer.go
Labels: approved, lgtm, size/S

#27 Add option to terminate transfer pods on completion
  transfer/rsync/server.go
  transfer/transfer.go
Labels: approved, lgtm, size/XS
